apiVersion: apps/v1
kind: Deployment
metadata:
  name: boqiangliang-com
  namespace: boqiangliang-com
  labels:
    app.kubernetes.io/name: boqiangliang-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: boqiangliang-com
  template:
    metadata:
      labels:
        app.kubernetes.io/name: boqiangliang-com
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: 192.168.0.201:5000/boqiangliang-com/web:sha-35934087d0cf1b0b407f25072acdb6df082f5d08
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests: { cpu: 25m, memory: 32Mi }
            limits: { cpu: 250m, memory: 256Mi }
