apiVersion: v1
kind: Service
metadata:
  name: boqiangliang-com
  namespace: boqiangliang-com
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: boqiangliang-com
  ports:
    - name: http
      port: 80
      targetPort: http
