apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boqiangliang-com-visitor-data
  namespace: boqiangliang-com
spec:
  volumeName: boqiangliang-com-visitor-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
